// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC15pDtyX5R8Qf8eYpE7d3Hkv5Tzf4KBo0',
    appId: '1:526819314915:web:c8602b7e044200a31509d6',
    messagingSenderId: '526819314915',
    projectId: 'test-5b91b',
    authDomain: 'test-5b91b.firebaseapp.com',
    databaseURL: 'https://test-5b91b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-5b91b.appspot.com',
    measurementId: 'G-EELVKYXFJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ZByQFhMtnADS5N5i3b8MJ1QarLEyZGI',
    appId: '1:526819314915:android:0b6a5b13457c4dbf1509d6',
    messagingSenderId: '526819314915',
    projectId: 'test-5b91b',
    databaseURL: 'https://test-5b91b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-5b91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSgNVVYvRa2SOD8ZPNJp1HLdrh8QDdBo',
    appId: '1:526819314915:ios:c27824e5f13f08ab1509d6',
    messagingSenderId: '526819314915',
    projectId: 'test-5b91b',
    databaseURL: 'https://test-5b91b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-5b91b.appspot.com',
    iosClientId: '526819314915-ap7bn34ojh10q7fm2jl2c5tj715n85v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.test',
  );
}
